# 1. BASE DE DATOS (POSTGRES)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: "sensores_db"
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "password123"
---
apiVersion: v1
kind: Service
metadata:
  name: db-sensores
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
---
# 2. BACKEND (PYTHON) - 2 RÉPLICAS
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-sensores
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: vicmiralo/backend-sensores:latest
          imagePullPolicy: Always # Cambiar a 'Always' si subes la imagen a Docker Hub
          ports:
            - containerPort: 5000
---
# 3. RED DE ACCESO (SERVICE)
apiVersion: v1
kind: Service
metadata:
  name: svc-backend
spec:
  type: NodePort # Cambiar a 'LoadBalancer' en una nube real (AWS/GCP)
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30080
