apiVersion: v1
kind: Service
metadata:
  name: token-proxy
spec:
  selector:
    app: token-proxy
  ports:
    - port: 9090
      targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: token-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: token-proxy
  template:
    metadata:
      labels:
        app: token-proxy
    spec:
      containers:
        - name: token-proxy
          image: vicmiralo/token-proxy:latest
          ports:
            - containerPort: 9090
          readinessProbe:
            tcpSocket:
              port: 9090
            initialDelaySeconds: 10
            periodSeconds: 5
