apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wso2-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: wso2am
spec:
  type: NodePort
  selector:
    app: wso2
  ports:
    - name: admin-console
      port: 9443
      targetPort: 9443
      nodePort: 31443
    - name: https-gateway
      port: 8243
      targetPort: 8243
      nodePort: 31243
    - name: http-gateway
      port: 8280
      targetPort: 8280
      nodePort: 31280
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wso2am
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wso2
  template:
    metadata:
      labels:
        app: wso2
    spec:
      containers:
        - name: wso2am
          image: wso2/wso2am:4.3.0
          env:
            - name: NODE_IP
              value: "127.0.0.1"
          ports:
            - containerPort: 9443
            - containerPort: 8243
            - containerPort: 8280
          volumeMounts:
            - name: wso2-data
              mountPath: /home/wso2carbon/wso2am-4.3.0/repository/database
          readinessProbe:
            httpGet:
              path: /services/Version
              port: 9763
            initialDelaySeconds: 120
            periodSeconds: 15
      volumes:
        - name: wso2-data
          persistentVolumeClaim:
            claimName: wso2-pvc
