name: Build and Push Images

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Descargar el código
        uses: actions/checkout@v4

      - name: 2. Login en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: 3. Build y Push del Backend
        run: |
          docker build -t vicmiralo/backend-sensores:latest .
          docker push vicmiralo/backend-sensores:latest

      - name: 4. Build y Push del Token Proxy
        run: |
          docker build -f Dockerfile.proxy -t vicmiralo/token-proxy:latest .
          docker push vicmiralo/token-proxy:latest
